/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.cognifide.aet.java-conventions")
}

dependencies {
    implementation("com.github.detro:browsermob-proxy-client:0.1.3")
    compileOnly(project(":jobs-api"))
    compileOnly(project(":selenium"))
    compileOnly("org.osgi:org.osgi.core:4.3.0")
    compileOnly("org.osgi:org.osgi.service.component.annotations:1.3.0")
    compileOnly("org.osgi:org.osgi.annotation:6.0.0")
    compileOnly("org.osgi:org.osgi.service.metatype.annotations:1.3.0")
    compileOnly("org.json:json:20180130")
    compileOnly("com.google.code.gson:gson:2.8.5")
    compileOnly("org.apache.httpcomponents:httpclient:4.4")
}

description = "AET :: OSGi Dependencies :: Proxy"
