/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.cognifide.aet.java-conventions")
}

dependencies {
    testImplementation("junit:junit:4.11")
    testImplementation("org.hamcrest:hamcrest-all:1.3")
    testImplementation("org.mockito:mockito-all:1.9.5")
    testImplementation("com.googlecode.zohhak:zohhak:1.1.1")
    testImplementation("xmlunit:xmlunit:1.2")
    testImplementation("uk.co.jemos.podam:podam:3.6.0.RELEASE")
    testImplementation("com.googlecode.catch-exception:catch-exception:1.2.0")
    testImplementation("org.skyscreamer:jsonassert:1.3.0")
    testImplementation("org.slf4j:slf4j-simple:1.7.7")
    testImplementation("org.assertj:assertj-core:3.11.1")
    compileOnly("org.osgi:org.osgi.service.component.annotations:1.3.0")
    compileOnly("org.osgi:org.osgi.annotation:6.0.0")
    compileOnly("org.osgi:org.osgi.service.metatype.annotations:1.3.0")
    compileOnly("org.osgi:org.osgi.core:4.3.0")
    compileOnly("org.jsoup:jsoup:1.11.3")
    compileOnly("com.googlecode.java-diff-utils:diffutils:1.3.0")
    compileOnly("org.apache.httpcomponents:fluent-hc:4.5.5")
    compileOnly("com.google.code.gson:gson:2.8.5")
    compileOnly("org.slf4j:slf4j-api:1.7.7")
    compileOnly("com.google.code.findbugs:jsr305:3.0.2")
    compileOnly(project(":communication-api"))
    compileOnly(project(":jobs-api"))
    compileOnly(project(":datastorage-api"))
    compileOnly(project(":validation-api"))
    compileOnly(project(":proxy"))
    compileOnly(project(":selenium"))
    compileOnly(project(":w3chtml5validator"))
}

description = "AET :: Core :: Jobs"
