/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.cognifide.aet.java-conventions")
}

dependencies {
    testImplementation("junit:junit:4.11")
    testImplementation("org.hamcrest:hamcrest-all:1.3")
    testImplementation("org.mockito:mockito-all:1.9.5")
    compileOnly(project(":communication-api"))
    compileOnly("org.osgi:org.osgi.service.component.annotations:1.3.0")
    compileOnly("org.osgi:org.osgi.annotation:6.0.0")
    compileOnly("org.osgi:org.osgi.service.metatype.annotations:1.3.0")
    compileOnly("org.apache.activemq:activemq-osgi:5.15.2")
    compileOnly("org.apache.felix:org.apache.felix.configadmin:1.8.16")
}

description = "AET :: Core :: Communication"
