/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.cognifide.aet.java-conventions")
}

dependencies {
    implementation("org.seleniumhq.selenium:jetty-repacked:7.6.1.1")
    implementation("org.seleniumhq.selenium:selenium-java:3.8.1")
    implementation("org.seleniumhq.selenium:selenium-api:3.8.1")
    implementation("org.seleniumhq.selenium:selenium-chrome-driver:3.8.1")
    implementation("org.seleniumhq.selenium:selenium-firefox-driver:3.8.1")
    implementation("org.seleniumhq.selenium:selenium-htmlunit-driver:2.52.0")
    implementation("org.seleniumhq.selenium:selenium-ie-driver:3.8.1")
    implementation("org.seleniumhq.selenium:selenium-remote-driver:3.8.1")
    implementation("org.seleniumhq.selenium:selenium-support:3.8.1")
    implementation("org.seleniumhq.selenium:selenium-server:3.8.1")
    implementation("org.apache.commons:commons-exec:1.3")
    implementation("com.sun.jna:jna:3.0.9")
    implementation("net.java.dev.jna:jna:3.3.0")
    implementation("net.java.dev.jna:platform:3.5.2")
}

description = "AET :: OSGi Dependencies :: Selenium"
