const listOfDataFilters = 
[
  {
    type: 'Accessibility',
    tag: "accessibility-filter",
    parameters: {
      error: {
        name: "Error",
        tag: "error",
        values: null,
        default: null,
        isMandatory: false,
        description: "The exact error message. At least one parameter is required, ignored if 'errorPattern' parameter is provided",
        current: null,
      },
      errorpattern: {
        name: "Error Pattern",
        tag: "errorPattern",
        values: null,
        default: null,
        isMandatory: false,
        description: "Regular expression that matches message text of issue to be filter out.",
        current: null,
      },
      principle: {
        name: "Principle",
        tag: "principle",
        values: null,
        default: null,
        isMandatory: false,
        description: "The exact accessibility issue principle.",
        current: null,
      },
      line: {
        name: "Line",
        tag: "line",
        values: null,
        default: null,
        isMandatory: false,
        description: "The line number in the file which the issue occurred in.",
        current: null,
      },
      column: {
        name: "Column",
        tag: "column",
        values: null,
        default: null,
        isMandatory: false,
        description: "The column number in the file which the issue occurred is.",
        current: null,
      },
    },
    deps: "Accessibility",
    dropTo: "accessibility-comparators",
    depType: null,
    group: "DataFilters",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/AccessibilityDataFilter",
  },
  {
    type: 'Extract Element',
    tag: "extract-element",
    parameters: {
      elementid: {
        name: "Element ID",
        tag: "elementId",
        values: null,
        default: null,
        isMandatory: false,
        description: "Id for the element to extract. One of these parameters is required.",
        current: null,
      },
      class: {
        name: "Class",
        tag: "class",
        values: null,
        default: null,
        isMandatory: false,
        description: "Class name for the element to extract. One of these parameters is required.",
        current: null,
      },
    },
    deps: "Source",
    dropTo: "source-comparators",
    depType: null,
    group: "DataFilters",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/ExtractElementDataFilter",
  },
  {
    type: 'JSErrors',
    tag: "js-errors-filter",
    parameters: {
      error: {
        name: "Error",
        tag: "error",
        values: null,
        default: null,
        isMandatory: false,
        description: "Exact error message. At least one parameter is required.",
        current: null,
      },
      source: {
        name: "Source",
        tag: "source",
        values: null,
        default: null,
        isMandatory: false,
        description: "Source file name in which error occurred. At least one parameter is required.",
        current: null,
      },
      errorpattern: {
        name: "Error Pattern",
        tag: "errorPattern",
        values: null,
        default: null,
        isMandatory: false,
        description: "Regular expression that matches message text of issue to be filter out. At least one parameter is required.",
        current: null,
      },
      line: {
        name: "Line",
        tag: "line",
        values: null,
        default: null,
        isMandatory: false,
        description: "Line number in file in which error occurred. At least one parameter is required.",
        current: null,
      },
    },
    deps: "JSErrors",
    dropTo: "jserrors-comparators",
    depType: null,
    group: "DataFilters",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/JSErrorsDataFilter",
  },
  {
    type: 'Remove Lines',
    tag: "remove-lines",
    parameters: {
      dataranges: {
        name: "Data Ranges",
        tag: "dataRanges",
        values: null,
        default: null,
        isMandatory: false,
        description: "Ranges of lines to remove from data. At least one parameter is required.",
        current: null,
      },
      patternRanges: {
        name: "Pattern Ranges",
        tag: "patternRanges",
        values: null,
        default: null,
        isMandatory: false,
        description: "Ranges of lines to remove from pattern. At least one parameter is required.",
        current: null,
      },
    },
    deps: "Source",
    dropTo: "source-comparators",
    depType: null,
    group: "DataFilters",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/RemoveLinesDataFilter",
  },
  {
    type: 'Remove Nodes',
    tag: "remove-nodes",
    parameters: {
      xpath: {
        name: "XPath",
        tag: "xpath",
        values: null,
        default: null,
        isMandatory: true,
        description: "XPath to node",
      },
    },
    deps: "Source",
    dropTo: "source-comparators",
    depType: null,
    group: "DataFilters",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/RemoveNodesDataFilter",
  },
  {
    type: 'Remove Regex',
    tag: "remove-regexp",
    parameters: {
      dataRegExp: {
        name: "Regex Expression",
        tag: "dataRegExp",
        values: null,
        default: null,
        isMandatory: false,
        description: "RegExp that will replace matched parts of data sources. At least one parameter is required.",
        current: null,
      },
      patternRegExp: {
        name: "Pattern Regext Expression",
        tag: "patternRegExp",
        values: null,
        default: null,
        isMandatory: false,
        description: "RegExp that will replace matched parts of pattern sources. At least one parameter is required.",
        current: null,
      },
      regExp: {
        name: "Regex Expression",
        tag: "regExp",
        values: null,
        default: null,
        isMandatory: false,
        description: "RegExp that will replace matched parts of pattern and data sources. At least one parameter is required.",
        current: null,
      },
    },
    deps: "Source",
    dropTo: "source-comparators",
    depType: null,
    group: "DataFilters",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/RemoveRegexDataFilter",
  },
  {
    type: 'Exclude',
    tag: "exclude",
    parameters: {
      url: {
        name: "URL",
        tag: "url",
        values: null,
        default: null,
        isMandatory: false,
        description: "Exact url to be removed from results. At least one parameter is required.",
        current: null,
      },
      pattern: {
        name: "Pattern",
        tag: "pattern",
        values: null,
        default: null,
        isMandatory: false,
        description: "Regex pattern that urls should match to be removed from results. At least one parameter is required.",
        current: null, 
      },
    },
    deps: "StatusCodes",
    dropTo: "statuscodes-comparators",
    depType: null,
    group: "DataFilters",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/StatusCodesDataFilters",
  },
  {
    type: 'Include',
    tag: "include",
    parameters: {
      url: {
        name: "URL",
        tag: "url",
        values: null,
        default: null,
        isMandatory: false,
        description: "Exact url to be removed from results. At least one parameter is required.",
        current: null,
      },
      pattern: {
        name: "Pattern",
        tag: "pattern",
        values: null,
        default: null,
        isMandatory: false,
        description: "Regex pattern that urls should match to be removed from results. At least one parameter is required.",
        current: null, 
      },
    },
    deps: "StatusCodes",
    dropTo: "statuscodes-comparators",
    depType: null,
    group: "DataFilters",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/StatusCodesDataFilters",
  },
  {
    type: 'W3CHTML5 Issues',
    tag: "w3c-filter",
    parameters: {
      message: {
        name: "Message",
        tag: "message",
        values: null,
        default: null,
        isMandatory: false,
        description: "Exact message text of the issue to be filtered out. *see notes below. At least one parameter is required.",
        current: null,
      },
      messagepattern: {
        name: "Message Pattern",
        tag: "messagePattern",
        values: null,
        default: null,
        isMandatory: false,
        description: "A regular expression that matches message text of the issue to be filtered out. At least one parameter is required.",
        current: null,
      },
      line: {
        name: "Line",
        tag: "line",
        values: null,
        default: null,
        isMandatory: false,
        description: "A line in the source file where the issue appears. At least one parameter is required.",
        current: null,
      },
      column: {
        name: "Column",
        tag: "column",
        values: null,
        default: null,
        isMandatory: false,
        description: "A column in the source file where the issue appears.. At least one parameter is required.",
        current: null,
      },
    },
    deps: "Source",
    dropTo: "source-comparators",
    depType: null,
    group: "DataFilters",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/W3CHTML5IssuesFilter",
  },
];

export default listOfDataFilters;