/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("com.cognifide.aet.java-conventions")
}

dependencies {
  compileOnly(project(":validation-api"))
  compileOnly("org.osgi:org.osgi.service.component.annotations:1.3.0")
  compileOnly("org.osgi:org.osgi.annotation:6.0.0")
  compileOnly("org.osgi:org.osgi.service.metatype.annotations:1.3.0")
  compileOnly("org.apache.commons:commons-lang3:3.7")

  testImplementation(project(":validation-api"))
  testImplementation("junit:junit:4.11")
  testImplementation("org.hamcrest:hamcrest-all:1.3")
  testImplementation("org.mockito:mockito-all:1.9.5")
  testImplementation("org.apache.commons:commons-lang3:3.7")
}

description = "AET :: Core :: Validation"
