/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  `java-library`
  `maven-publish`
//  `osgi`
}

repositories {
  mavenLocal()
  maven { url = uri("https://nexus.cognifide.com/content/groups/public") }
  maven { url = uri("https://nexus.cognifide.com/content/groups/private") }
  maven { url = uri("https://nexus.cognifide.com/content/repositories/cognifide-internal") }
  maven { url = uri("http://repo.adobe.com/nexus/content/groups/public/") }
  maven { url = uri("https://repo.maven.apache.org/maven2/") }
}

group = "com.cognifide.aet"
version = "3.4.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
  publications.create<MavenPublication>("maven") {
    from(components["java"])
  }
}

tasks.withType<JavaCompile> {
  options.encoding = "UTF-8"
}
