/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.cognifide.aet.java-conventions")
}

dependencies {
    compileOnly(project(":communication-api"))
    compileOnly(project(":datastorage-api"))
    compileOnly(project(":selenium"))
    compileOnly("org.apache.commons:commons-lang3:3.7")
    compileOnly("org.apache.httpcomponents:fluent-hc:4.5.5")
    compileOnly("org.codehaus.jackson:jackson-mapper-asl:1.9.13")
}

description = "AET :: API :: Jobs API"
