/*
 * AET
 *
 * Copyright (C) 2013 Cognifide Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
const listOfModifiers =
[
  {
    type: 'Click',
    tag: "click",
    parameters: {
      xpath: {
        name: "XPath",
        tag: "xpath",
        values: null,
        default: null,
        isMandatory: false,
        description: "XPath to element to be clicked",
        current: null,
      },
      css: {
        name: "CSS",
        tag: "css",
        values: null,
        default: null,
        isMandatory: false,
        description: "CSS selector to element to be clicked",
        current: null,
      },
      timeout: {
        name: "Timeout",
        tag: "timeout",
        values: null,
        default: "1000ms",
        isMandatory: false,
        description: "The timeout for the element to appear, in milliseconds. The max value of this parameter is 15000ms",
        current: null,
      },
    },
    deps: null,
    dropTo: "Collectors",
    group: "Modifiers",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/ClickModifier",
  },
  {
    type: 'Replace Text',
    tag: "replaceText",
    parameters: {
      value: {
        name: "Value",
        tag: "value",
        values: null,
        default: "",
        isMandatory: false,
        description: "New text value for given attribute or innterHTML of selected element",
        current: null,
      },
      attributename: {
        name: "Atrribute Name",
        tag: "attributeName",
        values: null,
        default: "innerHTML",
        isMandatory: false,
        description: "Attribute of selected element to be set, e.g. 'href' or 'value'",
        current: null,
      },
      xpath: {
        name: "XPath",
        tag: "xpath",
        values: null,
        default: null,
        isMandatory: false,
        description: "Xpath of element(s)",
        current: null,
      },
      css: {
        name: "CSS",
        tag: "css",
        values: null,
        default: null,
        isMandatory: false,
        description: "css selector of element(s)",
        current: null,
      },
      timeout: {
        name: "Timeout",
        tag: "timeout",
        values: null,
        default: "1000ms",
        isMandatory: false,
        description: "The timeout for the element to appear, in milliseconds. The max value of this parameter is 15000ms",
        current: null,
      },
    },
    deps: null,
    dropTo: "Collectors",
    group: "Modifiers",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/ReplaceTextModifier",
  },
  {
    type: 'Cookie',
    tag: "modify-cookie",
    parameters: {
      action: {
        name: "Action",
        tag: "action",
        values: ["add", "remove"],
        default: null,
        isMandatory: true,
        description: "Specifies what action should be taken with a given cookie",
        current: null,
      },
      cookiename: {
        name: "Cookie Name",
        tag: "cookie-name",
        values: null,
        default: null,
        isMandatory: true,
        description: "Cookie name",
        current: null,
      },
      cookievalue: {
        name: "Cookie Value",
        tag: "cookie-value",
        values: null,
        default: null,
        isMandatory: false,
        description: "Cookie Value, mandatory if 'add' action is selected",
        current: null,
      },
      cookiedomain: {
        name: "Cookie Domain",
        tag: "cookie-domain",
        values: null,
        default: null,
        isMandatory: false,
        description: "Cookie domain, used only if 'add' action is selected but it's not mandatory",
        current: null,
      },
      cookiepath: {
        name: "Cookie Path",
        tag: "cookie-path",
        values: null,
        default: null,
        isMandatory: false,
        description: "Cookie path, used only if 'add' action is selected but it's not mandatory",
        current: null,
      },
    },
    deps: null,
    dropTo: "Collectors",
    group: "Modifiers",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/CookieModifier",
  },
  {
    type: 'Header',
    tag: "header",
    parameters: {
      key: {
        name: "Key",
        tag: "key",
        values: null,
        default: null,
        isMandatory: true,
        description: "Key for the header",
        current: null,
      },
      value: {
        name: "Value",
        tag: "value",
        values: null,
        default: null,
        isMandatory: true,
        description: "Value for the header",
        current: null,
      },
    },
    deps: null,
    dropTo: "Collectors",
    group: "Modifiers",
    proxy: "true",
    wiki: "https://github.com/Cognifide/aet/wiki/HeaderModifier",
  },
  {
    type: 'Hide',
    tag: "hide",
    parameters: {
      xpath: {
        name: "XPath",
        tag: "xpath",
        values: null,
        default: null,
        isMandatory: false,
        description: "Xpath of element(s)",
        current: null,
      },
      css: {
        name: "CSS",
        tag: "css",
        values: null,
        default: null,
        isMandatory: false,
        description: "css selector of element(s)",
        current: null,
      },
      timeout: {
        name: "Timeout",
        tag: "timeout",
        values: null,
        default: "1000ms",
        isMandatory: false,
        description: "The timeout for the element to appear, in milliseconds. The max value of this parameter is 15000ms",
        current: null,
      },
      leaveblankspace: {
        name: "Leave Blank Space",
        tag: "leaveBlankSpace",
        values: ["true", "false"],
        default: null,
        isMandatory: false,
        description: "When set to true, blank and transparent space is left in place of the hidden element, otherwise, element is completely removed from the view.",
        current: null,
      },
    },
    deps: null,
    dropTo: "Collectors",
    group: "Modifiers",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/HideModifier",
  },
  {
    type: 'Login',
    tag: "login",
    parameters: {
      login: {
        name: "Login",
        tag: "login",
        values: null,
        default: "admin",
        isMandatory: false,
        description: "User's login",
        current: null,
      },
      password: {
        name: "Password",
        tag: "password",
        values: null,
        default: "admin",
        isMandatory: false,
        description: "User's password",
        current: null,
      },
      loginpage: {
        name: "Login Page",
        tag: "login-page",
        values: null,
        default: null,
        isMandatory: true,
        description: "Url to login page",
        current: null,
      },
      logininputselector: {
        name: "Login Input Selector",
        tag: "login-input-selector",
        values: null,
        default: "//input[@name='j_username']",
        isMandatory: false,
        description: "Xpath expression for login input",
        current: null,
      },
      loginpasswordselector: {
        name: "Login Password Selector",
        tag: "login-password-selector",
        values: null,
        default: "//input[@name='j_password']",
        isMandatory: false,
        description: "Xpath expression for password input",
        current: null,
      },
      submitbuttonselector: {
        name: "Submit Button Selector",
        tag: "submit-button-selector",
        values: null,
        default: "//*[@type='submit']",
        isMandatory: false,
        description: "Xpath expression for submit button",
        current: null,
      },
      logintokenkey: {
        name: "Login Token Key",
        tag: "login-token-key",
        values: null,
        default: "login-token",
        isMandatory: false,
        description: "Name for cookie we get after successfull login",
        current: null,
      },
      timeout: {
        name: "Timeout",
        tag: "timeout",
        values: null,
        default: "5000ms",
        isMandatory: false,
        description: "Number of milliseconds (between 0 and 10000) that modifier will wait to login page response after submiting credentials. It is also used between reattempts to log in.",
        current: null,
      },
      forcelogin: {
        name: "Force Login",
        tag: "force-login",
        values: null,
        default: "1000ms",
        isMandatory: false,
        description: "Enforces login even when login cookie is present.",
        current: null,
      },
      retrialnumber: {
        name: "Retrial Number",
        tag: "retrial-number",
        values: null,
        default: "3",
        isMandatory: false,
        description: "Number of reattempts to log in. It's a way to deal with unpredictable problem with logging in.",
        current: null,
      },
    },
    deps: null,
    dropTo: "Collectors",
    group: "Modifiers",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/LoginModifier",
  },
  {
    type: 'Resolution',
    tag: "resolution",
    parameters: {
      width: {
        name: "Width",
        tag: "width",
        values: null,
        default: null,
        isMandatory: false,
        description: "Window width",
        current: null,
      },
      height: {
        name: "Height",
        tag: "height",
        values: null,
        default: null,
        isMandatory: false,
        description: "Window height",
        current: null,
      },
    },
    deps: null,
    dropTo: "Collectors",
    group: "Modifiers",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/ResolutionModifier",
  },
  {
    type: 'Sleep',
    tag: "sleep",
    parameters: {
      duration: {
        name: "Duration",
        tag: "duration",
        values: null,
        default: null,
        isMandatory: true,
        description: "Sleep time, in milliseconds",
        current: null,
      },
    },
    deps: null,
    dropTo: "Collectors",
    group: "Modifiers",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/SleepModifier",
  },
  {
    type: 'WaitForPageLoaded',
    tag: "wait-for-page-loaded",
    parameters: null,
    deps: null,
    dropTo: "Collectors",
    group: "Modifiers",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/WaitForPageLoadedModifier",
  },
  {
    type: 'ExecuteJavaScript',
    tag: "executejavascript",
    parameters: {
      cmd: {
        name: "Command",
        tag: "cmd",
        values: null,
        default: null,
        isMandatory: false,
        description: "Javascript command that will be executed, not mandatory if snippetUrl is set",
        current: null,
      },
      snippeturl: {
        name: "Snippet URL",
        tag: "snippetUrl",
        values: null,
        default: null,
        isMandatory: false,
        description: "The url to external js snippet that will be executed, not mandatory if cmd is set",
        current: null,
      },
      basicauthusername: {
        name: "Basic Auth Username",
        tag: "basicAuthUsername",
        values: null,
        default: null,
        isMandatory: false,
        description: "For Basic HTTP Authentication header, only if basicAuthPassword is set",
        current: null,
      },
      basicauthpassword: {
        name: "Basic Auth Password",
        tag: "basicAuthPassword",
        values: null,
        default: null,
        isMandatory: false,
        description: "For Basic HTTP Authentication header, only if basicAuthUsername is set",
        current: null,
      },
    },
    deps: null,
    dropTo: "Collectors",
    group: "Modifiers",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/ExecuteJavaScriptModifier",
  },
  {
    type: 'WaitForElementToBeVisible',
    tag: "wait-for-element-to-be-visible",
    parameters: {
      xpath: {
        name: "XPath",
        tag: "xpath",
        values: null,
        default: null,
        isMandatory: false,
        description: "Xpath of element(s)",
        current: null,
      },
      css: {
        name: "CSS",
        tag: "css",
        values: null,
        default: null,
        isMandatory: false,
        description: "css selector of element(s)",
        current: null,
      },
      timeout: {
        name: "Timeout",
        tag: "timeout",
        values: null,
        default: "1000ms",
        isMandatory: false,
        description: "The timeout for the element to appear, in milliseconds. The max value of this parameter is 15000ms",
        current: null,
      },
    },
    deps: null,
    dropTo: "Collectors",
    group: "Modifiers",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/WaitForElementToBeVisibleModifier",
  },
  {
    type: 'WaitForImageCompletion',
    tag: "wait-for-image-completion",
    parameters: {
      xpath: {
        name: "XPath",
        tag: "xpath",
        values: null,
        default: null,
        isMandatory: false,
        description: "Xpath of element(s)",
        current: null,
      },
      css: {
        name: "CSS",
        tag: "css",
        values: null,
        default: null,
        isMandatory: false,
        description: "css selector of element(s)",
        current: null,
      },
      timeout: {
        name: "Timeout",
        tag: "timeout",
        values: null,
        default: "1000ms",
        isMandatory: false,
        description: "The timeout for the element to appear, in milliseconds. The max value of this parameter is 15000ms",
        current: null,
      },
    },
    deps: null,
    dropTo: "Collectors",
    group: "Modifiers",
    proxy: "false",
    wiki: "https://github.com/Cognifide/aet/wiki/WaitForImageCompletionModifier",
  },
];

export default listOfModifiers;