/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.cognifide.aet.java-conventions")
}

dependencies {
    testImplementation("junit:junit:4.11")
    testImplementation("org.hamcrest:hamcrest-all:1.3")
    testImplementation("org.mockito:mockito-all:1.9.5")
    testImplementation("com.github.stefanbirkner:system-rules:1.18.0")
    compileOnly(project(":communication-api"))
    compileOnly(project(":datastorage-api"))
    compileOnly(project(":validation-api"))
    compileOnly(project(":validation"))
    compileOnly("com.google.guava:guava:25.1-jre")
    compileOnly("commons-codec:commons-codec:1.11")
    compileOnly("org.osgi:org.osgi.service.component.annotations:1.3.0")
    compileOnly("org.osgi:org.osgi.annotation:6.0.0")
    compileOnly("org.osgi:org.osgi.service.metatype.annotations:1.3.0")
    compileOnly("com.google.code.gson:gson:2.8.5")
    compileOnly("org.osgi:org.osgi.compendium:4.2.0")
    compileOnly("commons-io:commons-io:2.6")
    compileOnly("org.apache.commons:commons-lang3:3.7")
    compileOnly("org.apache.servicemix.bundles:org.apache.servicemix.bundles.quartz:2.3.0_2")
    compileOnly("org.mongodb:mongo-java-driver:3.8.0")
}

description = "AET :: Core :: Data Storage"
